const initialProducts = [
  { id: 1, category: "Fast Food", name: "Fries", price: 200 },
  { id: 2, category: "Fast Food", name: "Mayo Garlic Fries", price: 300 },
  { id: 3, category: "Fast Food", name: "Beef Burger", price: 400 },
  { id: 4, category: "Fast Food", name: "Beef Cheese Burger", price: 480 },
  { id: 5, category: "Fast Food", name: "Beef Jumbo Burger", price: 700 },
  { id: 6, category: "Fast Food", name: "Chicken Burger", price: 400 },
  { id: 7, category: "Fast Food", name: "Chicken Cheese Burger", price: 480 },
  { id: 8, category: "Fast Food", name: "Chicken Jumbo Burger", price: 700 },
  { id: 9, category: "Fast Food", name: "Chicken Jumbo Cheese", price: 780 },
  { id: 10, category: "Fast Food", name: "Chicken Sandwich", price: 380 },

  { id: 11, category: "Fast Food", name: "Club Sandwich", price: 480 },
  { id: 12, category: "Fast Food", name: "Crispy Club Sandwich", price: 550 },
  { id: 13, category: "Fast Food", name: "Crispy Sandwich", price: 480 },
  { id: 14, category: "Fast Food", name: "Zinger Burger", price: 500 },
  { id: 15, category: "Fast Food", name: "Zinger Cheese", price: 580 },
  { id: 16, category: "Fast Food", name: "Zinger Jumbo", price: 800 },
  { id: 17, category: "Fast Food", name: "Zinger Jumbo Cheese", price: 880 },
  { id: 18, category: "Fast Food", name: "Chicken Breast Leg/Chest", price: 700 },
  { id: 19, category: "Fast Food", name: "Chicken Mayo Garlic Breast", price: 750 },
  { id: 20, category: "Fast Food", name: "Crispy Breast Leg/Chest", price: 750 },

  { id: 21, category: "Fast Food", name: "Spicy Breast Leg/Chest", price: 700 },
  { id: 22, category: "Fast Food", name: "Fajita Burger", price: 450 },
  { id: 23, category: "Fast Food", name: "Fajita Roll", price: 450 },
  { id: 24, category: "Fast Food", name: "Fajita Sandwich", price: 480 },
  { id: 25, category: "Fast Food", name: "Fajita Club Sandwich", price: 550 },
  { id: 26, category: "Fast Food", name: "Crispy Roll", price: 480 },
  { id: 27, category: "Fast Food", name: "Cheese Charges", price: 80 },
  { id: 28, category: "Fast Food", name: "Salad", price: 80 },
  { id: 29, category: "Fast Food", name: "Raita", price: 80 },
  { id: 30, category: "Fast Food", name: "Garlic", price: 80 },

  { id: 31, category: "Juices", name: "Apple Juice", price: 350 },
  { id: 32, category: "Juices", name: "Mosami Juice", price: 350 },
  { id: 33, category: "Juices", name: "Kino Juice", price: 350 },
  { id: 34, category: "Juices", name: "Grape Fruit Juice", price: 350 },
  { id: 35, category: "Juices", name: "Mix Juice", price: 350 },
  { id: 36, category: "Juices", name: "Falsa Juice", price: 200 },
  { id: 37, category: "Juices", name: "Anar Juice", price: 400 },
  { id: 38, category: "Juices", name: "Anar Juice Without Ice", price: 500 },
  { id: 39, category: "Juices", name: "ABC Juice", price: 300 },
  { id: 40, category: "Juices", name: "Ice Coffee", price: 400 },

  { id: 41, category: "Chaat", name: "Chana Papri", price: 220 },
  { id: 42, category: "Chaat", name: "Gol Gapy 1 Dozen", price: 280 },
  { id: 43, category: "Chaat", name: "Gol Gapy 1.5 Dozen", price: 360 },
  { id: 44, category: "Chaat", name: "Mix Chaat", price: 220 },
  { id: 45, category: "Chaat", name: "Spicy Fruit Chaat", price: 240 },
  { id: 46, category: "Chaat", name: "Cream Fruit Chaat", price: 270 },
  { id: 47, category: "Chaat", name: "Dahi Baray", price: 280 },
  { id: 48, category: "Chaat", name: "Pani Puri", price: 220 },
  { id: 49, category: "Chaat", name: "Meethi Puri", price: 220 },
  { id: 50, category: "Chaat", name: "Espresso Coffee", price: 300 },
  { id: 51, category: "Chaat", name: "Cappuccino", price: 300 },
  { id: 52, category: "Chaat", name: "Chicken Corn Soup", price: 240 },
  { id: 53, category: "Chaat", name: "Chicken Soup", price: 190 },

  { id: 54, category: "Shakes", name: "Banana Shake", price: 220 },
  { id: 55, category: "Shakes", name: "Cheeko Shake", price: 300 },
  { id: 56, category: "Shakes", name: "Mango Shake", price: 300 },
  { id: 57, category: "Shakes", name: "Khajur Shake", price: 300 },
  { id: 58, category: "Shakes", name: "Strawberry Shake", price: 300 },
  { id: 59, category: "Shakes", name: "Pineapple Shake", price: 300 },
  { id: 60, category: "Shakes", name: "Peach Shake", price: 300 },

  { id: 61, category: "Ice Cream", name: "Jelly Fruit", price: 350 },
  { id: 62, category: "Ice Cream", name: "Kulfa Faluda", price: 260 },
  { id: 63, category: "Ice Cream", name: "Special Faluda", price: 350 },
  { id: 64, category: "Ice Cream", name: "Shikar Puri Piyala", price: 400 },
  { id: 65, category: "Ice Cream", name: "Chocolate Topping", price: 350 },
  { id: 66, category: "Ice Cream", name: "Special Surprise", price: 450 },
  { id: 67, category: "Ice Cream", name: "Banana Split", price: 350 },
  { id: 68, category: "Ice Cream", name: "Special Pista", price: 400 },
  { id: 69, category: "Ice Cream", name: "Special Pineapple", price: 350 },
  { id: 70, category: "Ice Cream", name: "Special Tuti Fruity", price: 350 },
  { id: 71, category: "Ice Cream", name: "Special Strawberry", price: 350 },
  { id: 72, category: "Ice Cream", name: "Special Mango Ice Cream", price: 350 },
  { id: 73, category: "Ice Cream", name: "Special Mango Faluda", price: 350 },
  { id: 74, category: "Ice Cream", name: "Plain Faluda", price: 280 },

  { id: 75, category: "Ice Cream", name: "Peshawari Cup", price: 150 },
  { id: 76, category: "Ice Cream", name: "Pista Cup", price: 250 },
  { id: 77, category: "Ice Cream", name: "Pineapple Cup", price: 200 },
  { id: 78, category: "Ice Cream", name: "Tuti Fruity Cup", price: 200 },
  { id: 79, category: "Ice Cream", name: "Crunch Cup", price: 200 },
  { id: 80, category: "Ice Cream", name: "Chocolate Cup", price: 200 },
  { id: 81, category: "Ice Cream", name: "Cadbury Cup", price: 200 },
  { id: 82, category: "Ice Cream", name: "Strawberry Cup", price: 200 },
  { id: 83, category: "Ice Cream", name: "Blueberry Cup", price: 220 },
  { id: 84, category: "Ice Cream", name: "Cheese Cake Cup", price: 220 },
  { id: 85, category: "Ice Cream", name: "Badam Zafran Cup", price: 220 },
  { id: 86, category: "Ice Cream", name: "Mango Cup", price: 220 },
  { id: 87, category: "Ice Cream", name: "Oreo Cup", price: 220 },

  { id: 88, category: "Shakes", name: "Vanilla Ice Cream Shake", price: 270 },
  { id: 89, category: "Shakes", name: "Pista Shake", price: 400 },
  { id: 90, category: "Shakes", name: "Kulfa Shake", price: 350 },
  { id: 91, category: "Shakes", name: "Chocolate Shake", price: 350 },
  { id: 92, category: "Shakes", name: "Tuti Fruity Shake", price: 350 },
  { id: 93, category: "Shakes", name: "Pineapple Shake", price: 350 },
  { id: 94, category: "Shakes", name: "Cadbury Shake", price: 350 },
  { id: 95, category: "Shakes", name: "Oreo Shake", price: 350 },
  { id: 96, category: "Shakes", name: "Cold Coffee", price: 350 },
  { id: 97, category: "Shakes", name: "Mango Ice Cream Shake", price: 350 },
  { id: 98, category: "Shakes", name: "Blueberry Shake", price: 350 },
  { id: 99, category: "Shakes", name: "Kaju Shake", price: 350 }
];

export default initialProducts;